name = "url-shortener-admin"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# KV Namespace for storing links
# Run `npx wrangler# KV Namespace binding (Must match the ID used in Worker)
[[kv_namespaces]]
binding = "LINKS"
id = "9feb172d8fbe4c1aa230c8e906ad0b86"
preview_id = "4e43300c3c5348e0a5ff23685a845b80"

# R2 Bucket for storing OG images
# Run `npx wrangler r2 bucket create url-shortener-images` to create
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "url-shortener-images"
